version: '3.9'

services:
  sql-server-new:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TestProjetDotNet2025@"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql


volumes:
  sqlserver_data: